### ISSUE TITLE
the benchmark is incorrect

### ISSUE THREAD

**Issue by Waqar144** [igormironchik/md4qt#6]
The benchmark between char* and Qstring [here](https://github.com/igormironchik/md4qt/blob/main/tests/md_benchmark/README.md) is not measuring the same thing. char* preallocates the memory while Qstring doesn't. And no, even after using 'reserve', it won't be measuring the same thing. char* doesn't append anything while the other two are appending which involves at least 1 branch per function call

**Comment by igormironchik** [comment]
Hi.

What's actually happening in `QString::append()`? How it should work in your opinion?

Write me a thing that will "correctly" measure `char *` with `QString`.

**Comment by Waqar144** [comment]
Append/push_back tries to append something to the existing data, it might need to grow its capacity if there isn't enough memory. So, its not the same as pre-allocating all the memory and then doing `str[i] = 'c'` which is just writing to the memory directly.

But lets put that aside for a second and see what the compiler (clang) is doing: https://compiler-explorer.com/z/scod5KKss
it deleted the `char *` block and did nothing, just called std::chrono 2 times and showed you the measurement. So its entirely possible that the measurement is measuring something against nothing.

I would first try to ensure that the compiler doesn't optimize-out the char* portion, maybe use a benchmarking library, Qt has one or Google benchmark. I would also make sure the data that all the 3 string tests use is exactly the same. Then I would try something like:
```
        QString t(s.size() / 4 + 1, Qt::Uninitialized);
        {
            QChar *tt = t.data();
            qsizetype j = 0;
            for (auto i = 0; i < s.size(); ++i) {
                if (s[i] == QLatin1Char('a'))
                    tt[j++] = s[i];
            }
        }
```

**Comment by igormironchik** [comment]
If to be very meticulous then you are right. But my point was a little different... How usually does a developer work with `QString`? How usually does C developer do work with C-strings? Think from this point of view.

**Comment by Waqar144** [comment]
How does a developer work with something? I guess it depends on the scenario. If an append is needed in the code, then a C developer will write an append function. md4c definitely has its own append function. 

My aim was to just show you that the benchmark you link to as conclusion is broken. What you do with that info is upto you. In any case, thanks for creating a good markdown library for Qt users
